spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 452678149
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    hibernate:
      ddl-auto: none